version: '3.7'


x-defaults: &defaults
  logging:
    driver: json-file
    options:
      max-size: 2m
      max-file: 5


services:

    # dovecot:
    #     <<: *defaults
    #     image: isp-dovecot:local
    #     deploy:
    #         mode: replicated
    #         replicas: 1
    #         update_config:
    #             order: start-first
    #     networks:
    #         - mail

    roundcube:
        <<: *defaults
        image: isp-roundcube:local
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: start-first
        ports:
            - "8080:8080"
        networks:
            - mail

networks:
    mail:

volumes:
    mailstorage:
